/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vT8P8hnHRBq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import Link from "next/link";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function DashBoardPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center h-16 px-4 border-b bg-card shadow-sm sm:px-6">
        <div className="flex items-center gap-4">
          <Avatar className="border">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="grid gap-0.5">
            <div className="font-medium">John Doe</div>
            <div className="text-sm text-muted-foreground">Teacher</div>
          </div>
        </div>
        <nav className="ml-auto flex items-center gap-4">
          <Link
            href="#"
            className="text-muted-foreground hover:text-foreground"
            prefetch={false}
          >
            Classes
          </Link>
          <Link
            href="#"
            className="text-muted-foreground hover:text-foreground"
            prefetch={false}
          >
            Shared Documents
          </Link>
        </nav>
      </header>
      <main className="flex-1 p-4 sm:p-6 bg-background">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <ClassCard title="Math 101" />
          <ClassCard title="Biology 301" />
          <ClassCard title="History 401" />
          <ClassCard title="Chemistry 501" />
          <ClassCard title="Physics 601" />
        </div>
        <div className="mt-8 flex justify-end">
          <Button>Create New Class</Button>
        </div>
      </main>
    </div>
  );
}

function ClassCard({
  title,
  studentsNumber,
}: {
  title: string;
  studentsNumber?: number;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{title}</CardTitle>
      </CardHeader>
      <CardContent className="grid gap-2">
        <div className="flex items-center justify-between">
          <span className="text-muted-foreground">Students</span>
          <span>{studentsNumber ?? "-"}</span>
        </div>
        <Link href="#" className="text-primary" prefetch={false}>
          Class documents
        </Link>
      </CardContent>
    </Card>
  );
}
