/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CnR4Y34Q1ru
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Archivo } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import LoginForm from "./LoginForm";

export function LoginPage() {
  return (
    <div className="relative flex h-screen w-full items-center justify-center bg-gradient-to-b from-[#aac9eb] to-[#e795d1]">
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute inset-0 bg-[url('/waves.svg')] bg-cover bg-center bg-no-repeat animate-wave" />
      </div>
      <div className="relative z-10 w-full max-w-md rounded-lg bg-white p-8 shadow-lg">
        <LoginForm />
      </div>
    </div>
  );
}
